name: UrbanGames
favicon: null
layout_spectrum: 0.8059900577645749
typography_spectrum: 0.09267560066655278
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.0010084216482937336
  lightness: 0.18316175090149045
  saturation: 0.21723125968128443
  rhythmicContrast: 0.601299453759566
purpose: []
